name: ActionFun Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: CMAKE
      run: |
        mkdir build
        cd build
        cmake ../
    - name: Run make
      run: |
        cd build
        make
