name: ActionFun Build

on: [push]

jobs:
  build-linux:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: CMAKE
      run: |
        mkdir build
        cd build
        cmake ../
    - name: Run make
      run: |
        cd build
        make
    - uses: actions/upload-artifact@master
        with:
          name: linux-build
          path: ./build
          
  build-windows:
    
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: CMAKE
        run: |
          mkdir build
          cd build
          cmake ../
      - name: Run cl
        run: |
          cd build
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" ActionFun.sln
          ctest
      - uses: actions/upload-artifact@master
        with:
          name: windows-build
          path: ./build

    
      
          
