name: ActionFun Build

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: CD
      run: cd
    - name: ls
      run: ls
    - name: Run cmake
      run: cmake [options] -S . -B build
    - name: Run make
      run: make ./build
