name: ActionFun Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: CD
      run: cd
    - name: ls
      run: ls
    - name: Run cmake
      run: cmake [options] -S . -B build
    - name: go to build
      run: |
        cd build
        ls
    - name: Run make
      run: make
